default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bristol_help_desk
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: bristol_helpdesk_test
  username: postgres
  password: root
  host: localhost
  port: 5432

production:
  <<: *default
  database: bristol_helpdesk_production
  username: postgres
  password: <%= ENV["BRISTOL_HELPDESK_DATABASE_PASSWORD"] %>